// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaviscaAssessment.Context;

namespace TaviscaAssessment.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210706144423_updated model 354456")]
    partial class updatedmodel354456
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TaviscaAssessment.Models.Ingredients", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "",
                            Name = "Dough/Flour",
                            Price = 10
                        },
                        new
                        {
                            Id = 2,
                            Image = "",
                            Name = "Pizza Dough Mix",
                            Price = 20
                        },
                        new
                        {
                            Id = 3,
                            Image = "",
                            Name = "Deep Dish Pizza Dough Mix",
                            Price = 30
                        },
                        new
                        {
                            Id = 4,
                            Image = "",
                            Name = "Ultra Thin/Low Carb Pizza Dough",
                            Price = 40
                        },
                        new
                        {
                            Id = 5,
                            Image = "",
                            Name = "Gluten Free Pizza Crust",
                            Price = 50
                        },
                        new
                        {
                            Id = 6,
                            Image = "",
                            Name = "Pizza Sauce",
                            Price = 80
                        },
                        new
                        {
                            Id = 7,
                            Image = "",
                            Name = "Pizza Sauce Seasoning",
                            Price = 80
                        });
                });

            modelBuilder.Entity("TaviscaAssessment.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("OrderStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PizzaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PizzaId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("TaviscaAssessment.Models.Pizza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ingredients")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PizaaTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("PizzaTypeId")
                        .HasColumnType("int");

                    b.Property<int>("TotalCost")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PizzaTypeId");

                    b.ToTable("Pizza");
                });

            modelBuilder.Entity("TaviscaAssessment.Models.PizzaIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<int?>("IngredientsId")
                        .HasColumnType("int");

                    b.Property<int>("PizzaTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IngredientsId");

                    b.ToTable("PizzaIngredient");
                });

            modelBuilder.Entity("TaviscaAssessment.Models.PizzaType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PizzaImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PizzaType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PizzaImage = "",
                            TypeName = "Margherita"
                        },
                        new
                        {
                            Id = 2,
                            PizzaImage = "",
                            TypeName = "Peppy Paneer"
                        },
                        new
                        {
                            Id = 3,
                            PizzaImage = "",
                            TypeName = "Mexican Green Wave"
                        },
                        new
                        {
                            Id = 4,
                            PizzaImage = "",
                            TypeName = "CHEESE N CORN"
                        });
                });

            modelBuilder.Entity("TaviscaAssessment.Models.Order", b =>
                {
                    b.HasOne("TaviscaAssessment.Models.Pizza", "Pizza")
                        .WithMany("Order")
                        .HasForeignKey("PizzaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pizza");
                });

            modelBuilder.Entity("TaviscaAssessment.Models.Pizza", b =>
                {
                    b.HasOne("TaviscaAssessment.Models.PizzaType", null)
                        .WithMany("Pizza")
                        .HasForeignKey("PizzaTypeId");
                });

            modelBuilder.Entity("TaviscaAssessment.Models.PizzaIngredient", b =>
                {
                    b.HasOne("TaviscaAssessment.Models.Ingredients", "Ingredients")
                        .WithMany("PizzaIngredient")
                        .HasForeignKey("IngredientsId");

                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("TaviscaAssessment.Models.Ingredients", b =>
                {
                    b.Navigation("PizzaIngredient");
                });

            modelBuilder.Entity("TaviscaAssessment.Models.Pizza", b =>
                {
                    b.Navigation("Order");
                });

            modelBuilder.Entity("TaviscaAssessment.Models.PizzaType", b =>
                {
                    b.Navigation("Pizza");
                });
#pragma warning restore 612, 618
        }
    }
}
